### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#175]
Oh man, you guys are killing me lol.  I created a new project from scratch so the branch plugin downloaded fresh again.  And once again the builds are failing.  Looks like you changed a class name or something?

/Users/build/Build/app/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:10:12: error: 
      cannot find interface declaration for 'BranchSDK'; did you mean 'Branch'?
@interface BranchSDK()
           ^~~~~~~~~
           Branch
In module 'Branch' imported from /Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:8:
Veoci/Plugins/io.branch.sdk/Branch.framework/Headers/Branch.h:112:12: note: 'Branch' declared here
@interface Branch : NSObject
           ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:18:17: warning: 
      cannot find interface declaration for 'BranchSDK'; did you mean 'Branch'?
@implementation BranchSDK
                ^
In module 'Branch' imported from /Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:8:
Veoci/Plugins/io.branch.sdk/Branch.framework/Headers/Branch.h:112:12: note: 'Branch' declared here
@interface Branch : NSObject
           ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:52:23: error: 
      expected a type
- (id)handleDeepLink:(CDVInvokedUrlCommand*)command
                      ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:62:31: error: 
      expected a type
- (void)continueUserActivity:(CDVInvokedUrlCommand*)command
                              ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:83:22: error: 
      expected a type
- (void)initSession:(CDVInvokedUrlCommand*)command
                     ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:146:19: error: 
      expected a type
- (void)setDebug:(CDVInvokedUrlCommand*)command
                  ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:158:26: error: 
      expected a type
- (void)getAutoInstance:(CDVInvokedUrlCommand*)command
                         ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:163:35: error: 
      expected a type
- (void)getLatestReferringParams:(CDVInvokedUrlCommand*)command
                                  ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:178:34: error: 
      expected a type
- (void)getFirstReferringParams:(CDVInvokedUrlCommand*)command
                                 ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:193:22: error: 
      expected a type
- (void)setIdentity:(CDVInvokedUrlCommand*)command
                     ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:212:37: error: 
      expected a type
- (void)registerDeepLinkController:(CDVInvokedUrlCommand*)command
                                    ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:219:30: error: 
      expected a type
- (void)userCompletedAction:(CDVInvokedUrlCommand*)command
                             ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:246:17: error: 
      expected a type
- (void)logout:(CDVInvokedUrlCommand*)command
                ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:263:22: error: 
      expected a type
- (void)loadRewards:(CDVInvokedUrlCommand*)command
                     ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:282:24: error: 
      expected a type
- (void)redeemRewards:(CDVInvokedUrlCommand*)command
                       ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:318:27: error: 
      expected a type
- (void)getCreditHistory:(CDVInvokedUrlCommand*)command
                          ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:337:38: error: 
      expected a type
- (void)createBranchUniversalObject:(CDVInvokedUrlCommand*)command
                                     ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:398:23: error: 
      expected a type
- (void)registerView:(CDVInvokedUrlCommand*)command
                      ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:416:27: error: 
      expected a type
- (void)generateShortUrl:(CDVInvokedUrlCommand*)command
                          ^
/Users/sosbuild/Build/soschat-mobile-3.0/trunk/Veoci/platforms/ios/Veoci/Plugins/io.branch.sdk/BranchSDK.m:475:25: error: 
      expected a type
- (void)showShareSheet:(CDVInvokedUrlCommand*)command
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.

**Comment by gabaum10** [comment]
Looks like it was broken by f77c158e291cba701853fa40c21c30d57c1ece54?

**Comment by gabaum10** [comment]
Looks like this could be resolved by f77c158e291cba701853fa40c21c30d57c1ece54?

**Comment by tkuse** [comment]
same problem here for me!

thought i screwed things up after updating to latest cordova ios platform 4.2.0

**Comment by aaustin** [comment]
Sorry about that guys. NPM requires a different file configuration due to some weirdness, and I had to tweak the header reference in ~ 6 different places to accommodate. I merged that fix to master.

**Comment by gabaum10** [comment]
Thanks, that seems to have done the trick.  Was just poor timing on my part to delete the project first thing in the morning.
