### ISSUE TITLE
Deep linking not working using v3.0.1 - possibly because of user tracking error?

### ISSUE THREAD

**Issue by Wade-McDaniel** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#498]
I've upgraded to 3.0.1 so I can use the GDPR/disableTracking support in our apps. I was told that deep-links should still work even with disableTracking(true);

My problem now is that deep links don't seem to work at all, regardless of if I set disableTracking(true), disableTracking(false), or just omit that line entirely.

In iOS I see a message associated with branch.io: BNCServiceInterface.m(618) Error: Network Service error: Error Domain=io.branch.sdk.error Code=1015 "User tracking is disabled." UserInfo={NSLocalizedDescription=User tracking is disabled.}.

**Questions:**

1. It doesn't seem like Branch.disableTracking(boolean) affects this message: am i trying to call the wrong function name?
2. Would the error I included here cause deep links to not work - do I need user-tracking for deep linking after all? And if so how does that affect app users in the EU?

Thank you!

**Comment by Wade-McDaniel** [comment]
Here's what I've tried, in case some code helps

```
$ionicPlatform.ready(function(){
  if (typeof Branch !== 'undefined') {
    try {
      Branch.disableTracking(false); // disable tracking before initializing the session to avoid sending user data
    } catch (ex) {
    Branch.initSession().then(function(data) {
      // when initSession runs is when I see the "user tracking is disabled" message
    });
  }
});
```

**Comment by Wade-McDaniel** [comment]
I answered my own #2 question: the answer is no, deep links still work (but are super long and ugly)

But question #1 remains: at launch I see the "tracking disabled" message, and also on app resume when I check if user is switching to my app from a shared link an unhanded exception is thrown about "tracking disabled" as well

**Comment by sequoiaat** [comment]
Yes, deep links work even with tracking disabled. 
However short URL does not get generated, so that's why you see the long URL.

Yes, the function name is correct - Branch.disableTracking(boolean).
Please check if you are calling this function similarly in resume, 
that is $ionicPlatform.resume(function()

Please refer https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#initialize-branch-features
Section on initialize branch features

**Comment by Wade-McDaniel** [comment]
Thanks!

But as of my post from 21 hours ago, even tho I use Branch.disableTracking(false); (so tracking should be enabled) I still get the unhandled exception that "tracking is disabled", and my URLs are still long and ugly.

disableTracking = false should _enable_ tracking and make my URLs short like they were in 2.6.17, right? But they aren't. That exception and resulting lack of short URLs is my only bug now.

Has it been reported before that other plugins can cause this behavior in the branch plugin? I didn't see it in Google searches, but just in case here are the plugins I'm using:

```
<plugin name="cordova-plugin-ionic-webview" spec="^1.1.16" />
<plugin name="cordova-plugin-app-version" spec="^0.1.9" />
<plugin name="cordova-plugin-device" spec="^1.1.6" />
<plugin name="cordova-plugin-dialogs" spec="^1.3.3" />
<plugin name="cordova-plugin-google-analytics" spec="^1.8.3" />
<plugin name="cordova-plugin-googleplus" spec="^5.1.1">
<variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.1234567890" />
</plugin>
<plugin name="cordova-plugin-screen-orientation" spec="^1.4.3" />
<plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
<plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
<plugin name="cordova-plugin-x-socialsharing" spec="^5.3.2" />
<plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
<plugin name="org.pbernasconi.progressindicator" spec="https://github.com/pbernasconi/cordova-progressIndicator.git" />
<plugin name="cordova-plugin-media" spec="https://github.com/Wade-McDaniel/cordova-plugin-media.git">
<variable name="MICROPHONE_USAGE_DESCRIPTION" value=" " />
</plugin>
<plugin name="cordova-plugin-background-mode" spec="https://github.com/Wade-McDaniel/cordova-plugin-background-mode.git" />
<plugin name="cordova-plugin-music-controls" spec="https://github.com/Wade-McDaniel/cordova-music-controls-plugin.git" />
<plugin name="cordova-plugin-facebook4" spec="^1.9.1">
<variable name="APP_ID" value="1234567890" />
<variable name="APP_NAME" value="Wade" />
</plugin>
<plugin name="cordova-plugin-ios-keychain" spec="^3.0.1" />
<plugin name="cordova-plugin-statusbar" spec="https://github.com/apache/cordova-plugin-statusbar.git" />
<plugin name="cordova-custom-config" spec="^5.0.2" />
<plugin name="cordova-plugin-progressindicator" spec="https://github.com/pbernasconi/cordova-progressIndicator.git" />
<plugin name="cordova-plugin-network-information" spec="^2.0.1" />
```

**Comment by trelee** [comment]
@Wade-McDaniel I've just run in to this issue as well. The iOS plugin doesn't currently allow the disableTracking setting to be set to false. See #501 for details.
