### ISSUE TITLE
iOS build failed with error v1.indexof() is not found

### ISSUE THREAD

**Issue by shahbazkhan054** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#139]
_1>  Executing "after_prepare"  hook for all plugins.
1>  Resolving module name for cordova-lib/src/plugman/platforms => ../plugman/platforms
1>  Resolving module name for cordova-lib/src/plugman/platforms/ios => ../plugman/platforms/ios
1>  Resolving module name for cordova-common/src/ConfigParser/ConfigParser => cordova-common/src/ConfigParser/ConfigParser
1>  Failed to build app for buildNumber 17445: v1.indexOf is not a function
1>MSBUILD : cordova-build error : Error: Remote build error from the build server Build failed with error v1.indexOf is not a function -
1>  Error Remote build error from the build server Build failed with error v1.indexOf is not a function - {1}_

**Comment by shahbazkhan054** [comment]
**After Updating to 2.0.3 I am getting error with file path -**

_** In file included from /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/21837/cordovaApp/platforms/ios/Trestro/Plugins/io.branch.sdk/BranchSDK.m:8:
1>  Trestro/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found
1>  #import <Branch/Branch.h>
1>          ^
1>  1 error generated.**_

**Comment by renesansz** [comment]
Does this error shows upon upon upgrading your Cordova?
Can you try to re-install the plugin?
```
1. Remove the platforms, cordova platform rm <ios/android>
2. Remove the plugin cordova plugin rm io.branch.sdk
3. Re-install the platform, cordova platform add <ios/android>
4. Re-install the plugin, refer to the instructions
```
As of the moment, the plugin works as intended.
Let me know if this solves the issue. 👍

**Comment by shahbazkhan054** [comment]
Error is still coming, right it is stuck on vi.indexof() error. I have added another platform version 4.1.1. 
then added plugin and then built. i have added following config in my config.xml 

  <branch-config>
    <ios-team-id value="*****" />
    <host name="xxxx.app.link" scheme="https" />
  </branch-config>

I think indexof error is because of this. Once i remove this then i get branch/branch.h file not found error.

**Comment by renesansz** [comment]
@shahbazkhan054 , hmmm...couldn't really replicate the issue. not sure what's causing the error.
could you post your full `config.xml` file?

**Comment by shahbazkhan054** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<widget xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:vs="http://schemas.microsoft.com/appx/2014/htmlapps" id="com.xxxxx" version="1.5.6" xmlns="http://www.w3.org/ns/widgets" defaultlocale="en-US">
  <name>xxxx</name>
  <description>xxx</description>
  <author href="http://xxxx.com" email="hello@xxxx.com">xxxx Team</author>
  <content src="index.html" />
  <access origin="*" />
  <vs:features />
  <preference name="SplashScreen" value="screen" />
  <!--<preference name="windows-target-version" value="8.1" />--> 
  <plugin name="cordova-plugin-whitelist" version="1" />
  <allow-intent href="http://*/*" />
  <allow-intent href="https://*/*" />
  <allow-intent href="tel:*" />
  <allow-intent href="sms:*" />
  <allow-intent href="mailto:*" />
  <allow-intent href="geo:*" />
  <platform name="android">
    <allow-intent href="market:*" />
    <allow-intent href="trestro://*" />
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*" />
    <allow-intent href="itms-apps:*" />
  </platform>
  <platform name="android">
    <icon src="res/icons/android/icon-36-ldpi.png" density="ldpi" />
    <icon src="res/icons/android/icon-48-mdpi.png" density="mdpi" />
    <icon src="res/icons/android/icon-72-hdpi.png" density="hdpi" />
    <icon src="res/icons/android/icon-96-xhdpi.png" density="xhdpi" />
  </platform>
  <platform name="ios">
    <!-- iOS 8.0+ -->
    <!-- iPhone 6 Plus  -->
    <icon src="res/icons/ios/icon-60-3x.png" width="180" height="180" />
    <!-- iOS 7.0+ -->
    <!-- iPhone / iPod Touch  -->
    <icon src="res/icons/ios/icon-60.png" width="60" height="60" />
    <icon src="res/icons/ios/icon-60-2x.png" width="120" height="120" />
    <!-- iPad -->
    <icon src="res/icons/ios/icon-76.png" width="76" height="76" />
    <icon src="res/icons/ios/icon-76-2x.png" width="152" height="152" />
    <!-- iOS 6.1 -->
    <!-- Spotlight Icon -->
    <icon src="res/icons/ios/icon-40.png" width="40" height="40" />
    <icon src="res/icons/ios/icon-40-2x.png" width="80" height="80" />
    <!-- iPhone / iPod Touch -->
    <icon src="res/icons/ios/icon-57.png" width="57" height="57" />
    <icon src="res/icons/ios/icon-57-2x.png" width="114" height="114" />
    <!-- iPad -->
    <icon src="res/icons/ios/icon-72.png" width="72" height="72" />
    <icon src="res/icons/ios/icon-72-2x.png" width="144" height="144" />
    <!-- iPhone Spotlight and Settings Icon -->
    <icon src="res/icons/ios/icon-small.png" width="29" height="29" />
    <icon src="res/icons/ios/icon-small-2x.png" width="58" height="58" />
    <!-- iPad Spotlight and Settings Icon -->
    <icon src="res/icons/ios/icon-50.png" width="50" height="50" />
    <icon src="res/icons/ios/icon-50-2x.png" width="100" height="100" />
  </platform>
  <platform name="windows">
    <icon src="res/icons/windows/Square150x150Logo.scale-100.png" width="150" height="150" />
    <icon src="res/icons/windows/Square150x150Logo.scale-240.png" width="360" height="360" />
    <icon src="res/icons/windows/Square30x30Logo.scale-100.png" width="30" height="30" />
    <icon src="res/icons/windows/Square310x310Logo.scale-100.png" width="310" height="310" />
    <icon src="res/icons/windows/Square44x44Logo.scale-100.png" width="44" height="44" />
    <icon src="res/icons/windows/Square44x44Logo.scale-240.png" width="106" height="106" />
    <icon src="res/icons/windows/Square70x70Logo.scale-100.png" width="70" height="70" />
    <icon src="res/icons/windows/Square71x71Logo.scale-100.png" width="71" height="71" />
    <icon src="res/icons/windows/Square71x71Logo.scale-240.png" width="170" height="170" />
    <icon src="res/icons/windows/StoreLogo.scale-100.png" width="50" height="50" />
    <icon src="res/icons/windows/StoreLogo.scale-240.png" width="120" height="120" />
    <icon src="res/icons/windows/Wide310x150Logo.scale-100.png" width="310" height="150" />
    <icon src="res/icons/windows/Wide310x150Logo.scale-240.png" width="744" height="360" />
  </platform>
  <platform name="wp8">
    <icon src="res/icons/wp8/ApplicationIcon.png" width="99" height="99" />
    <icon src="res/icons/wp8/Background.png" width="159" height="159" />
  </platform>
  <platform name="android">
    <splash src="res/screens/android/screen-hdpi-landscape.png" density="land-hdpi" />
    <splash src="res/screens/android/screen-ldpi-landscape.png" density="land-ldpi" />
    <splash src="res/screens/android/screen-mdpi-landscape.png" density="land-mdpi" />
    <splash src="res/screens/android/screen-xhdpi-landscape.png" density="land-xhdpi" />
    <splash src="res/screens/android/screen-hdpi-portrait.png" density="port-hdpi" />
    <splash src="res/screens/android/screen-ldpi-portrait.png" density="port-ldpi" />
    <splash src="res/screens/android/screen-mdpi-portrait.png" density="port-mdpi" />
    <splash src="res/screens/android/screen-xhdpi-portrait.png" density="port-xhdpi" />
  </platform>
  <platform name="ios">
    <splash src="res/screens/ios/screen-iphone-portrait.png" width="320" height="480" />
    <splash src="res/screens/ios/screen-iphone-portrait-2x.png" width="640" height="960" />
  <splash src="res/screens/ios/screen-ipad-portrait.png" width="768" height="1024" />
    <splash src="res/screens/ios/screen-ipad-portrait-2x.png" width="1536" height="2048" />
    <splash src="res/screens/ios/screen-ipad-landscape.png" width="1024" height="768" />
    <splash src="res/screens/ios/screen-ipad-landscape-2x.png" width="2048" height="1536" />
    <splash src="res/screens/ios/screen-iphone-568h-2x.png" width="640" height="1136" />
    <splash src="res/screens/ios/screen-iphone-portrait-667h.png" width="750" height="1334" />
    <splash src="res/screens/ios/screen-iphone-portrait-736h.png" width="1242" height="2208" />
    <splash src="res/screens/ios/screen-iphone-landscape-736h.png" width="2208" height="1242" />
  </platform>
  <platform name="windows">
    <splash src="res/screens/windows/SplashScreen.scale-100.png" width="620" height="300" />
    <splash src="res/screens/windows/SplashScreen.scale-240.png" width="1152" height="1920" />
    <splash src="res/screens/windows/SplashScreenPhone.scale-240.png" width="1152" height="1920" />
  </platform>
  <platform name="wp8">
    <splash src="res/screens/wp8/SplashScreenImage.png" width="768" height="1280" />
  </platform>
  <plugin name="cordova-plugin-device" version="1.1.2" />
  <plugin name="cordova-plugin-device-orientation" version="1.0.3" />
  <plugin name="cordova-plugin-inappbrowser" version="1.2.1" />
  <plugin name="cordova-plugin-network-information" version="1.2.1" />
  <plugin name="cordova-plugin-geolocation" version="2.1.0" />
  <plugin name="cordova-plugin-x-toast" version="2.5.0" src="https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git" />
  <plugin name="com.cordova.plugins.sms" version="0.1.10" src="https://github.com/cordova-sms/cordova-sms-plugin.git" />
  <plugin name="cordova-plugin-statusbar" version="2.1.3" />
  <plugin name="cordova-plugin-dialogs" version="1.2.2-dev" src="https://github.com/apache/cordova-plugin-dialogs.git" />
  <plugin name="cordova-plugin-ios-longpress-fix" version="1.1.0" src="https://github.com/EddyVerbruggen/cordova-plugin-ios-longpress-fix.git" />  
  <preference name="android-minSdkVersion" value="19" />
  <preference name="android-targetSdkVersion" value="22" />
  <plugin name="es6-promise-plugin" version="3.0.2" />
  <plugin name="cordova-plugin-splashscreen" version="4.0.0" src="https://github.com/apache/cordova-plugin-splashscreen.git" />
  <!-- Custom Preferences -->
  <platform name="ios">
    <preference name="target-device" value="handset" />
  </platform>
  <preference name="deployment-target" value="7" />
  <preference name="AutoHideSplashScreen" value="false" />
  <preference name="ShowSplashScreenSpinner" value="false" />
  <preference name="FadeSplashScreen" value="false" />
  <preference name="SplashShowOnlyFirstTime" value="false" />
  <preference name="KeepRunning" value="True" />
  <preference name="ShowTitle" value="True" />
  <preference name="InAppBrowserStorageEnabled" value="True" />
  <preference name="SuppressesIncrementalRendering" value="True" />
  <preference name="exit-on-suspend" value="false" />
  <preference name="LoadUrlTimeoutValue" value="70000" />
  <preference name="Orientation" value="portrait" />
  <preference name="DisallowOverscroll" value="true" />
  <preference name="webviewbounce" value="false" />
  <preference name="StatusBarOverlaysWebView" value="false" />
  <preference name="StatusBarBackgroundColor" value="#ff6600" />
  <preference name="StatusBarStyle" value="lightcontent" />
  <preference name="BackupWebStorage" value="cloud" />
  <plugin name="phonegap-plugin-push" version="1.6.3" src="https://github.com/phonegap/phonegap-plugin-push.git">
    <param name="SENDER_ID" value="xxxxxxx" />
  </plugin>

<branch-config>
    <ios-team-id value="xxxxxx" />
    <host name="xxxx.app.link" scheme="https" />
  </branch-config>
</widget>
```

this is my complete config.xml file. One more thing, I am using visual studio code for apache cordova and cordova cli varsion 6.1.1.

**Comment by renesansz** [comment]
Hey @shahbazkhan054 ,
I've finally found the error in the hook script, I think this is because the semver comparison in the script have a variable type issue.
I've submitted #141 to fix this build error, hoping this would resolve the issue.

**Comment by shahbazkhan054** [comment]
Thank you very much for the fix. 
I am new to git. Can you please tell me how can i get that fixed version and test it?
Thanks again.

**Comment by renesansz** [comment]
@shahbazkhan054 ,
You simply have to upgrade/update the plugin by doing `cordova plugin update io.branch.sdk --save`.
Let me know if this issue is fixed. 👍

**Comment by shahbazkhan054** [comment]
I am using visual studio tools for apache cordova, i reinstalled it but it is having some installation errors.
That's why I am not able to verify it. I will fix my issues and confirm you soon.

**Comment by shahbazkhan054** [comment]
Hi, I have tried reinstalling the plugin but still getting the error,

```
** In file included from /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/21837/cordovaApp/platforms/ios/Trestro/Plugins/io.branch.sdk/BranchSDK.m:8:
1> Trestro/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found
1> #import 
1> ^
1> 1 error generated.**
```

**Comment by renesansz** [comment]
@shahbazkhan054 ,
Weird it shouldn't have any build errors anymore :(
So far I can't replicate the missing header error issue. Can you provide some details like cordova-cli version and also are you building through Phonegap?

Also, can you try to re-install everything by doing the following:
```
1. Remove the platforms folder
2. Remove the plugins folder
3. Install the platform, cordova platform add <ios/android>
4. Install the plugin, refer to the instructions
```

**Comment by shahbazkhan054** [comment]
I tried the above method but error is still coming regarding missing header.
```
1>  CompileC build/Trestro.build/Debug-iphoneos/Trestro.build/Objects-normal/armv7/AppDelegate+BranchSdk.o Trestro/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
1>      cd /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios
1>      export LANG=en_US.US-ASCII
1>      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/paarthdesai/.taco_home/node_modules/taco-remote-lib/2.2.0/node_modules/taco-remote-lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
1>      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/80/9zw9sqz503d2t8kx33ply9640000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/Trestro-generated-files.hmap -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/Trestro-own-target-headers.hmap -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/Trestro-all-target-headers.hmap -iquote /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/Trestro-project-headers.hmap -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/device/include -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/device/usr/local/lib/include -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/UninstalledProducts/include -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/UninstalledProducts/iphoneos/include -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/device -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/DerivedSources/armv7 -I/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/DerivedSources -F/Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/device -FTrestro/Plugins/io.branch.sdk -include /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/sharedpch/Trestro-Prefix-ampapzrhsntqrlfqtqytbuvxspet/Trestro-Prefix.pch -MMD -MT dependencies -MF /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/Objects-normal/armv7/AppDelegate+BranchSdk.d --serialize-diagnostics /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/Objects-normal/armv7/AppDelegate+BranchSdk.dia -c /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/Trestro/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m -o /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/build/Trestro.build/Debug-iphoneos/Trestro.build/Objects-normal/armv7/AppDelegate+BranchSdk.o
1>  /Users/paarthdesai/.taco_home/remote-builds/taco-remote/builds/1918/cordovaApp/platforms/ios/Trestro/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m:10:9: fatal error: 'Branch/Branch.h' file not found
1>  #import <Branch/Branch.h>
1>          ^
1>  1 error generated.
```

I am using visual studio tools for apache cordova with CLI version 6.1.1.

**Comment by aaustin** [comment]
Ah - the problem here is that it can't find the iOS SDK framework. It's located in the repository here: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/tree/master/src/ios/dependencies. Can you see if VS properly imported the framework?

If you're just adding the raw files to the SDK (found [here](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/tree/master/src/ios/dependencies/Branch-SDK)), the header imports need to change to `#import "Branch.h"`.. etc.

**Comment by shahbazkhan054** [comment]
I just checked VS has not copied Branch-SDK folder to platform. I added it manually but still getting file not found error.

**Comment by aaustin** [comment]
Can you confirm that the headers Branch.h are included there? If so, can you try changing the code for BranchSDK.h and AppDelegate+BranchSdk.m to reference `#import "Branch.h"` instead of the `<Branch/Branch.h>` format

**Comment by kuchida** [comment]
Adding the following to [plugin.xml](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/9cc4ae4760fcebec0358c4c12c9d7df851cca9ca/plugin.xml#L107) solved the problem for me.
```xml
<header-file src="src/ios/dependencies/Branch-SDK/BranchView.h" />
<header-file src="src/ios/dependencies/Branch-SDK/BranchViewHandler.h" />
```

**Comment by aaustin** [comment]
ackkkk fixing now

**Comment by aaustin** [comment]
Should be resolved in 2.1.2. Apologies for the bad deploy.

**Comment by renesansz** [comment]
@aaustin , should I submit a PR for this?

**Comment by renesansz** [comment]
submitted PR #151

**Comment by shahbazkhan054** [comment]
I am still getting the same error even after updating plugin with latest version 2.1.2.

1>  xxxx/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found
1>  #import <Branch/Branch.h>
1>          ^
1>  1 error generated.

**Comment by shahbazkhan054** [comment]
It's working now as I made two changes :(code between ** is changed)

AppDelegate+Branch.m
```
#import "AppDelegate.h"
#import **<dependencies/Branch.framework/Versions/A/Headers/Branch.h>**
```
Branch.h
```
#import **<dependencies/Branch.framework/Versions/A/Headers/Branch.h>**
#import <Branch/BranchLinkProperties.h>
#import <Branch/BranchUniversalObject.h>
#import <Cordova/CDV.h>
```

**Comment by aaustin** [comment]
Ah. Very very strange. That must be a Visual Studio requirement.

**Comment by shahbazkhan054** [comment]
Yes I think, Actually after reinstalling platform and plugin it is even working on "branch.h" path.I am still not able to understand issue but found a weird workaround.
